export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    GETDATA_REQUEST: 'GETDATA_REQUEST',
    GETDATA_SUCCESS: 'GETDATA_SUCCESS',
    GETDATA_FAILURE: 'GETDATA_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    HANDLE_SUCCESS : "HANDLE_SUCCESS",
    CLEAR_STATE : "CLEAR_STATE"
};
